---
- hosts: localhost
  connection: local
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"

  tasks: 
  - name: Install Base Packages
    become: true
    become_method: sudo
    package: 
      name: 
        - htop
        - tmux
        - neovim
        - neofetch
        - zsh
        - timeshift
        - spice-vdagent 
        - zsh-syntax-highlighting
        - curl
        - cargo
        - cmake
        - pkg-config
        - libfreetype6-dev
        - libfontconfig1-dev
        - libxcb-xfixes0-dev

  - name: Sublime Text
    become: yes
    become_method: sudo
    unarchive:
      src: https://download.sublimetext.com/sublime_text_3_build_3211_x64.tar.bz2
      dest: /opt
      remote_src: yes
      owner: "{{ user }}"

  - name: Sublime Symbolic Link
    become: yes
    become_method: sudo
    file:
      src: "/opt/sublime_text_3/sublime_text"
      dest: "/usr/bin/sublime"
      state: link  

  - name: Sublime Desktop File
    copy:
      src: files/sublime_desktop
      dest: /opt/sublime_text_3/sublime_text.desktop
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Sublime Text Install Desktop File
    become: yes
    become_method: sudo
    shell: 
      chdir: /opt/sublime_text_3/
      cmd: desktop-file-install --dir=/usr/share/applications sublime_text.desktop

  - name: Make git Folder
    file:
      path: "{{ home }}/git/"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775

  - name: Make Terminator Folder
    file:
      path: "{{ home }}/.config/terminator/"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775

  - name: Make NeoVIM Folder
    file:
      path: "{{ home }}/.config/nvim"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775

  - name: Copy Alias File
    copy:
      src: files/alias
      dest: "{{ home }}/.alias"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy BASH File
    copy:
      src: files/bash
      dest: "{{ home }}/.bashrc"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy Powerlevel10k
    copy:
      src: files/p10k
      dest: "{{ home }}/.p10k.zsh"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy NeoVIM config
    copy:
      src: files/neovim
      dest: "{{ home }}/.config/nvim/init.vim"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy Terminator config
    copy:
      src: files/terminator
      dest: "{{ home }}/.config/terminator/config"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Clone ohmyzsh
    git:
      clone: yes
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: "{{ home }}/git/ohmyzsh"
      update: yes

  - name: Install ohmyzsh
    shell:
      chdir: "{{ home }}/git/ohmyzsh/tools"
      executable: "{{ home }}/git/ohmyzsh/tools/install.sh"
      cmd: install.sh

  - name: Clone Powerlevel10k
    git:
      clone: yes
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: "{{ home }}/.oh-my-zsh/custom/themes/powerlevel10k"
      update: yes

  - name: ZSH Syntax Highlighting
    git:
      clone: yes
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
 
  - name: Clone Nerd-Fonts
    git:
      clone: yes
      repo: https://github.com/ryanoasis/nerd-fonts.git
      dest: "{{ home }}/git/nerd-fonts"

  - name: Copy ZSH File
    copy:
      src: files/zsh
      dest: "{{ home }}/.zshrc"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Make Alacritty Folder
    file:
      path: "{{ home }}/.config/alacritty"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775

  - name: Copy Alacritty config
    copy:
      src: files/alacritty
      dest: "{{ home }}/.config/alacritty/alacritty.yml"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Copy TMUX config
    copy:
      src: files/tmux
      dest: "{{ home }}/.tmux.conf"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Clone Alacritty
    git:
      clone: yes
      repo: https://github.com/alacritty/alacritty.git
      dest: "{{ home }}/git/alacritty"

  - name: Cargo Install Alacritty
    shell: 
      chdir: "{{ home }}/git/alacritty/"
      cmd: cargo build --release

  - name: Copy Alacritty bin
    become: yes
    become_method: sudo
    copy:
      src: "{{ home }}/git/alacritty/target/release/alacritty"
      dest: "/usr/local/bin"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775

  - name: Copy Alacritty Logo
    become: yes
    become_method: sudo
    copy:
      src: "{{ home }}/git/alacritty/extra/logo/alacritty-term.svg"
      dest: "/usr/share/pixmaps/Alacritty.svg"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775

  - name: Copy Alacritty Desktop File
    become: yes
    become_method: sudo
    shell:
      chdir: "{{ home }}/git/alacritty/"
      cmd: desktop-file-install extra/linux/Alacritty.desktop
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0775

  - name: Update Installed Apps
    become: yes
    become_method: sudo
    shell: update-desktop-database